# Generated by Django 4.1 on 2024-03-31 13:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForgotPassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('time', models.DateTimeField(auto_now=True)),
                ('fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additionalPhotos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
